#!/bin/bash
# Generic bash/zsh Initialization

umask 002

ismac() {
    [[ "Darwin" == "$(uname)" ]]
}

islinux() {
    [[ "Linux" == "$(uname)" ]]
}

exists() {
    hash $1 2>/dev/null
}


# Path
[[ -d ~/bin ]] && export PATH=~/bin:$PATH

export CDPATH=.:~:~/working
ismac   && CDPATH=$CDPATH:~/Documents/nci:/usr/local:/usr/local/Cellar:/Volumes
islinux && CDPATH=$CDPATH:/media:/var/run/media/$USER

# Homebrew paths first
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="$PATH:/usr/AMS2/net/scripts"

# Make python, pip run version 3 stuff
ismac && export PATH="/usr/local/opt/python/libexec/bin:$PATH"
ismac && export PATH="/usr/local/Cellar/gnu-sed/4.8/libexec/gnubin:$PATH"


if [[ -z "$TMUX" ]]; then
    if [[ -f /bin/launchctl ]]; then
        # Finder launched programs need this path ?
        /bin/launchctl setenv PATH "$PATH"
    fi
fi


#Bash
export HISTCONTROL=erasedups


#Common Shell tools
export LANG=en_US.UTF-8

export GREP_OPTIONS="--color --exclude-dir=.hg --exclude-dir=.git"
# Not graphical or hg ci will abort without -f or --remote-wait
export VISUAL='nvim'
export EDITOR=$VISUAL
# Enable colors in ls on Mac/BSD
export CLICOLOR=1

# Less
export LESS="FRX"

#pkg-config path
#pkg-config --cflags cairo
#pkg-config --libs cairo
export PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig:/opt/X11/share/pkgconfig:/opt/local/lib/pkgconfig:/usr/lib/pkgconfig

if ismac; then
  # use gnu versions of these tools.  Must be installed with
  # brew install findutils gnu-sed coreutils
  alias find=gfind
  alias sed=gsed
  alias mktemp=gmktemp
fi

# Ruby Version Manager
## Add RVM to PATH for scripting
# [[ -d "$HOME/.rvm/bin" ]] && PATH=$PATH:$HOME/.rvm/bin
# Load RVM into a shell session *as a function*
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Python
#export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

# Rust Language
# export PATH="$HOME/.cargo/bin:$PATH"

if ismac; then
    # autojump
    [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
fi

# Asciidoc
export XML_CATALOG_FILES=/usr/local/etc/xml/catalog

# iterm
if ismac; then
    function tabname {
        printf "\e]1;$1\a"
    }

    function winname {
        printf "\e]2;$1\a"
    }
fi

# Aliases
alias l='ls -lh'
alias la='ls -lAh'
alias ll='ls -lh'
alias vi='vim'
if exists nvim; then
    alias vim='nvim'
fi
if exists mvim; then
    alias gvim='mvim'
fi

if [ -t 0 ]; then # term test?
    # Turn off TTY "start" and "stop" commands in all interactive shells.
    # They default to C-q and C-s, Bash uses C-s to do a forward history search.
    stty start ''
    stty stop  ''
    stty -ixon # disable XON/XOFF flow control
    stty ixoff # enable sending (to app) of start/stop characters
    stty ixany # let any character restart output, not only start character
    stty -echoctl # Disable ^C from printing when Ctrl-C is pressed
fi

# Commands
_do_open() {
    type xdg-open > /dev/null 2>&1 && xdg-open $1
    type gnome-open > /dev/null 2>&1 && gnome-open $1

    # Mac
    type open > /dev/null 2>&1 && open $1
}

openbb() {
    # Form URL from user and repository name from default path
    local URL=$(gsed -nre 's;.*bitbucket.org/([a-z][-_a-z0-9]*)/([a-z][-_a-z0-9]+)$;http://bitbucket.org/\1/\2;p' <(hg paths))
    if [[ -n $URL ]]; then
        _do_open $URL
    else
        echo "No BitBucket path found!"
    fi
}

# vim:ft=sh
