link cmd/apple_container.snippets           .config/cmd
link cmd/apple_container.sh                 .config/cmd
link cmd/brew.snippets                      .config/cmd
link cmd/checksum.snippets                  .config/cmd
link cmd/diskutil.snippets                  .config/cmd
link cmd/diskutil.sh                        .config/cmd
link cmd/gnu.snippets                       .config/cmd
link cmd/launchctl.snippets                 .config/cmd
link cmd/launchctl.sh                       .config/cmd
link cmd/lima.snippets                      .config/cmd
link cmd/lima.sh                            .config/cmd
link cmd/luarocks.snippets                  .config/cmd
link cmd/mediainfo.snippets                 .config/cmd
link cmd/net.snippets                       .config/cmd
link cmd/npm.snippets                       .config/cmd
