[[mgr.prepend_keymap]]
on   = ["g", "p"]
run  = "plugin fzcd"
desc = "Go ~/.paths | FZF"

[[mgr.prepend_keymap]]
on   = ["g", "j"]
run  = "plugin autojump"
desc = "autojump"

[[mgr.prepend_keymap]]
on   = ["g", "J"]
run  = "plugin autojump -- FZF"
desc = "autojump | FZF"
