[[mgr.prepend_keymap]]
on   = ["g", "p"]
run  = "plugin fzcd"
desc = "Go ~/.paths | FZF"

[[mgr.prepend_keymap]]
on   = ["g", "j"]
run  = "plugin autojump"
desc = "autojump"

[[mgr.prepend_keymap]]
on   = ["g", "J"]
run  = "plugin autojump -- FZF"
desc = "autojump | FZF"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "F"
run  = "shell --confirm 'open .'"
desc = "Open the current directory in Finder"
