[mgr]
ratio = [0, 4, 3]
sort_dir_first = false
sort_by = "mtime"
sort_reverse = true

[opener]
acrobat = [
    { run = 'open -a "Adobe Acrobat.app" "$@"', orphan = true, for = "macos", desc = "Acrobat"}
]
preview = [
    { run = 'open -a Preview.app "$@"', orphan = true, for = "macos", desc = "Preview" }
]

[[open.prepend_rules]]
mime = "application/pdf"
use = [ "preview", "acrobat" ]
