[mgr]
ratio = [0, 4, 3]
sort_dir_first = false
sort_by = "mtime"
sort_reverse = true

[tasks]
image_bound = [65535, 65535]

[preview]
# 1200 is a good balance between visible and slow
image_quality = 50
max_width       = 800
max_height       = 800

[opener]
acrobat = [
    { run = 'open -a "Adobe Acrobat.app" "$@"', orphan = true, for = "macos", desc = "Acrobat"}
]
preview = [
    { run = 'open -a Preview.app "$@"', orphan = true, for = "macos", desc = "Preview" }
]

[[open.prepend_rules]]
mime = "application/pdf"
use = [ "preview", "acrobat" ]
