"Default : aegimrLtT  linux : aciM
set guioptions=rLt

" MacVim specific settings
if has("gui_macvim")
    " allows option to be used as alt with <M>
    set macmeta

    macmenu File.Print key=<nop>
    map <D-p> :CtrlP<CR>
    imap <D-p> <C-p>
    macmenu File.New\ Window key=<nop>
    imap <D-n> <C-n>

    macmenu File.Save key=<nop>
    imap <D-s> <esc>:w<CR>
    map <D-s> :w<CR>

    macmenu &File.Close key=<nop>
    nmap <D-w> :CommandW<CR>
    imap <D-w> <Esc>:CommandW<CR>
endif

