" NOTE: FormatMatch osx application prevents visual block selections from being yanked and pasted

" Set this to higher numbers to increase vim's speed (while losing features)
"  0 : Slowest, all features enabled
"  1 : Disables features that slow down vim the most
"  2 : Disables custom color highlighting
"  3 : Disables syntax highlighting all together
let g:speed=0

" vim: set ft=vim:

set nocompatible
" vi-compatible sentences have two spaces after them.
set cpo+=J " Recognize sentences by two spaces after punctuation

scriptencoding utf-8
set encoding=utf-8
set fileencoding=utf-8

set tags=tags
set tags+=../tags
set tags+=../../tags
set tags+=../../../tags
"set tags+=../../../../tags
"set tags+=../../../../../tags
" mkdir -p tags
" cd ~/tags
" ctags -R /usr/include
"set tags+=/home/chad/tags/tags.inc

if &shell =~# 'fish$'
    set shell=sh
endif

set expandtab                   " tabs are spaces, not tabs (et)
set shiftwidth=4                " use indents of 4 spaces (sw)
set tabstop=4                   " an indentation every four columns (ts)
set softtabstop=8               " Column text should be easily aligned with this at 8
set shiftround                  " >> and << will round to the nearest shiftwidth
set smarttab                    " Make shiftwidth affect spaces added when tabs are typed

set linebreak                   " When wrap is on, break at word boundaries

set nospell
set spelllang=en_us
set dictionary=/usr/share/dict/words
set thesaurus=~/dotfiles/mthesaur.txt

" Enable 'vim: tw=80 noet sw=2' in files
set modeline
if g:speed < 1
    " This slows things down a fair amount
    set cursorline
endif

if g:speed > 0
    set synmaxcol=200
    set lazyredraw
    set regexpengine=1
endif

set printoptions=left:2cm,top:1in,right:2cm,bottom:1in,duplex:off,paper:letter,syntax:y,number:y

" Ignore settings
let g:ack_wildignore=0 " Otherwise error ack.vim line 31
set wildignore=tags,a.out,depmod,*.so,*.a,*.o,*.dep,*.class,*.pyc

set hidden                      " Allow buffers (unsaved) in the background (like tabs)
set virtualedit=block           " Block mode allows cursor to go where spaces don't exist
"set virtualedit+=onemore        " Allow cursor to stay one character past the end of the line
set autoindent                  " indent at the same level of the previous line
set cindent
set smartindent                 " New lines start indented appropriately
set nowrap                      " wrap long lines

" iTerm2 in osx likes unnamed, not unnamedplus
if $TMUX == ''
    set clipboard=unnamed
endif

set textwidth=0                 " Used in autoformatting (tw)
if g:speed < 1
    set colorcolumn=+0              " Use textwidth variable
endif

"set comments=sl:/*,mr:*,elx:*/  " auto format comment blocks with gq see help format-comments
set comments=n:\"
set comments=n:>
set comments=n://
set comments=sr:/***,m:*,elx:***/
" set formatoptions+=a " to get format as you type in comments (fo)
" set formatoptions-=a " to disable
set formatoptions+=j " Delete comment character when joining commented lines

" works for normal and insert.  I want insert to work
set backspace=indent,eol,start

set incsearch                   " find as you type search
set hlsearch                    " highlight search terms
set ignorecase                  " case insensitive search
set smartcase                   " case sensitive when upper is present in search

set number
if version > 703
    " This is a redraw hog!
    " set relativenumber
endif

set splitbelow
set splitright

set showcmd " Shows partial key sequences

set scrolloff=3      " minimum lines to keep above and below cursor
set scrolljump=5     " lines to scroll when cursor leaves screen
set sidescrolloff=5

set display+=lastline

set noshowmatch                   " Use pi_paren plugin instead
set matchtime=5
"let loaded_matchparen = 1       " Disable pi_paren plugin
" see guicursor, cpoptions
"disable/enable with NoMatchParen/DoMatchParen
"highlight MatchParen cterm=lightblue guibg=lightblue
"highlight MatchParen guibg=lightred
set matchpairs=(:),{:},[:]

set wildmenu                    " show list instead of just completing
set wildmode=list:longest,full  " command <Tab> completion, list matches, then longest common part, then all.

set laststatus=2                " 2 - Always show status line

" statusline Colors
"   directory
hi default link User1 Directory
"   filename
hi default link User2 String
"   filetype
hi default link User3 Type

set statusline=\ \ %1*\ %{getcwd()}\ %0*                        " current root or dir
set statusline+=\ \ %2*\ %f%m\ %0*                              " Filename/Modified
set statusline+=%=                                              " Right Aligned
set statusline+=%v/%l/%L\                                       " cursor pos
set statusline+=\ \ %3*\ %{&ft}\ %0*\                           " Filetype
set statusline+=%{&fenc?&fenc:&enc}/%{&ff}\                     " Encoding/EOL
set statusline+=%w                                              " Preview
set statusline+=%r\                                             " Read Only

set history=1000 " : command history size
set sessionoptions-=options  " Don't store mappings when using mksession
set viewoptions-=options     " Don't store mappings when using mkview

" Highlight problematic whitespace
set list
set listchars=tab:>\ ,trail:+,extends:#,nbsp:.
if has('multi_byte')
    if $TERM != "konsole"
        " For some reason UTF characters are not showing in vim
        set listchars=trail:·,precedes:«,extends:»,tab:▸·
        set listchars+=nbsp:·
        "set listchars+=eol:↲
    endif
endif

" show the ruler (only if statusline isn't shown - laststatus=0 or 1
set ruler
set rulerformat=%30(%=%y%m%r%w\ %l,%r%V\ %p%)

set autoread
set nobackup
if $TMUX == ''
    set swapfile   " Swap file lets you know the buffer is open in another window
else
    set noswapfile
endif

set backupdir=~/.vim/backup
if !isdirectory(&backupdir)
    call mkdir(&backupdir, "p")
endif

set directory=~/.vim/tmp  " Where the swap file will go
if !isdirectory(&directory)
    call mkdir(&directory, "p")
endif

"set undofile                " Save undo's after file closes
"set undodir=$HOME/.vim/undo " where to save undo histories
"set undolevels=1000         " How many undos
"set undoreload=10000        " number of lines to save for undo

" Help escape take effect immediately.  Since escape is part of a key code,
" sometimes escape doesn't take immediately if not followed by another
" character.  ttimeoutlen=0 (set to a low value) tells vim to escape now.
"
" If on MAC, may need to
"   mv /etc/vimrc /etc/vimrc.disabled
set timeout timeoutlen=1000 ttimeout ttimeoutlen=0

"Paste helper
set mouse=a

if executable('ag')
    " Make :grep use the silver searcher (ag)
    set grepprg=ag\ --nogroup\ --nocolor\ --column\  "this comment prevents trailing space on this line
    "set grepprg=grep\ -n\
    set grepformat=%f:%l:%c:%m
endif


""""""""""""""""""""""""""""""""" Autocmds:
augroup vimdiff
    autocmd!
    " Run diffupdate everytime Cursor is moved
    autocmd CursorMoved,CursorMovedI * if &diff == 1 | diffupdate | endif
    " in case CursorMoved,CursorMovedI is too CPU intensive
    "autocmd BufWritePost * if &diff == 1 | diffupdate | endif
augroup END

augroup quickfix
    autocmd!
    " Open quickfix window by default after helpgrep or the like
    autocmd QuickFixCmdPost [^l]* nested cwindow
    autocmd QuickFixCmdPost    l* nested lwindow
augroup END


""""""""""""""""""""""""""""""""" Keyboard Mappings: Global Settings
let mapleader = ','
let maplocalleader = ' '

nnoremap <c-w>f :call FocusWindow(140)<cr>

""""""""""""""""""""""""""""""""" Keyboard Mappings: Built-in Modifications
nnoremap Q :echom "Exmode Disabled"<cr>
" Yank from the cursor to the end of the line, to be consistent with C and D.
nnoremap Y y$
nnoremap x "_x

if has('osx')
    nmap <silent> K <Plug>DashSearch
endif

" Make any necesary parent directories
command! -nargs=1 E execute('silent! !mkdir -p "$(dirname "<args>")"') <Bar> e <args>

" Removes highlighting on insert
" https://vi.stackexchange.com/questions/10407/stop-highlighting-when-entering-insert-mode
autocmd InsertEnter * setlocal nohlsearch
autocmd InsertLeave * setlocal hlsearch
inoremap <silent><Esc> <Esc>:nohl<CR>
inoremap <silent><C-c> <Esc>:nohl<CR>
nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>

"Saving helpers
nnoremap <C-s> :update<CR>
inoremap <C-s> <esc>:update<CR>

nnoremap <A-x> :update<CR>:!<Up><CR>
inoremap <A-x> <esc>:update<CR>

imap <S-Insert> <MiddleMouse>

if !has('nvim')
    " Shougo/unite.vim
    nnoremap <localleader>p :Unite history/yank<cr>
else
    nnoremap <localleader>p :Denite neoyank<cr>
endif

"junegunn/fzf.vim
if !has("gui_running")
    imap <c-x><c-k> <plug>(fzf-complete-word)
    imap <c-x><c-f> <plug>(fzf-complete-path)
    imap <c-x><c-j> <plug>(fzf-complete-file-ag)
    imap <c-x><c-l> <plug>(fzf-complete-line)
endif

nnoremap ]f :next<cr>
nnoremap [f :prev<cr>

nnoremap ]b :bnext<cr>
nnoremap [b :bprev<cr>

nnoremap ]q :cnext<cr>
nnoremap [q :cprev<cr>
nnoremap ]Q :cnewer<cr>
nnoremap [Q :colder<cr>

" Location List :lgrep :lvimgrep
nnoremap ]l :lnext<cr>
nnoremap [l :lprev<cr>
nnoremap ]L :lnewer<cr>
nnoremap [L :lolder<cr>

" Tag Stack (Although I normall use the jump list CTRL-O)
nnoremap ]t :tag<cr>
nnoremap [t :pop<cr>

" Jump List
nnoremap ]j <c-I>
nnoremap [j <c-O>

" Change List
"mhinz/vim-signify
nmap ]c <plug>(signify-next-hunk)
nmap [c <plug>(signify-prev-hunk)

" Matching Tag List - Loaded with :tselect or g]
nnoremap ]g :tnext<cr>
nnoremap [g :tprevious<cr>

" CTRL-W_} then cycle through matches in preview window
nnoremap ]p :ptnext<cr>
nnoremap [p :ptprev<cr>

nnoremap ]T :tabnext<cr>
nnoremap [T :tabprevious<cr>

nnoremap ]w :wincmd l<cr>
nnoremap [w :wincmd h<cr>

" Wrapped lines goes down/up to next row, rather than next line in file.
"nnoremap j gj
"nnoremap k gk

"NOTE: tpope/vim-abolish coerce:
" crs to snake_case
" crm to MixedCase
" crc to camelCase
" cru to UPPER_CASE

"junegunn/fzf.vim
nmap <leader><tab> <plug>(fzf-maps-n)

""""""""""""""""""""""""""""""""" Keyboard Mappings: Visual
" Delete to black hole
vnoremap <leader>d "_d

" visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv


""""""""""""""""""""""""""""""""" Keyboard Mappings: Settings Modification
nnoremap \2 :setlocal sw=2 ts=2<cr>
nnoremap \3 :setlocal sw=3 ts=3<cr>
nnoremap \4 :setlocal sw=4 ts=4<cr>
nnoremap \8 :setlocal sw=8 ts=8<cr>
nnoremap \t :setlocal expandtab!<cr>
nnoremap \\2 :set sw=2 ts=2<cr>
nnoremap \\3 :set sw=3 ts=3<cr>
nnoremap \\4 :set sw=4 ts=4<cr>
nnoremap \\8 :set sw=8 ts=8<cr>
nnoremap \\t :set expandtab!<cr>

" This facilitates copying multiple lines of text from terminal vim
nnoremap \n :set number relativenumber<cr>
nnoremap \N :set nonumber norelativenumber<cr>

" Reload to force line endings
nnoremap \\d :e ++ff=dos<cr>
nnoremap \\u :e ++ff=unix<cr>
nnoremap \d :set ff=dos<cr>
nnoremap \u :set ff=unix<cr>

":retab to convert

nnoremap \s :set spell!<cr>        " Toggles Spelling

nnoremap \w :set wrap<cr>    " Go into wrap mode
nnoremap \W :set nowrap<cr>  " Exit wrap mode

nnoremap \\v :source $MYVIMRC<cr>

" junegunn/rainbow_parentheses.vim
nnoremap \r :RainbowParentheses!!<cr>

" tpope/vim-commentary
" For changing comment characters in html/script/style
nnoremap \c/  :set commentstring=//\ %s<cr>
nnoremap \c*  :set commentstring=/*\ %s\ */<cr>
nnoremap \c-  :set commentstring=<!--\ %s\ --><cr>

" mhinz/vim-signify
nmap \+ :SignifyToggle<cr>
" jlfwong/vim-mercenary'
nmap \b :HGblame<cr>
" cskeeters/vim-hg
nmap \a :HgAnnotate<cr>
" gd - go diff when cursor is over number
nmap \l :HgGLog<cr>
" gd - go diff when cursor is over number

" Toggle diff
nmap <space>d :ToggleDiff<cr>

" When text doesn't highlight
nnoremap \\5 :syntax sync minlines=500<cr>
nnoremap \\x :syntax sync fromstart<cr>

""""""""""""""""""""""""""""""""" Keyboard Mappings: Directory

" Change Working Directory to that of the current file
nnoremap <c-j>. :lcd %:p:h<cr>
nnoremap <c-j>u :lcd ..<cr>
nnoremap <c-j>1 :lcd ..<cr>
nnoremap <c-j>2 :lcd ../..<cr>
nnoremap <c-j>3 :lcd ../../..<cr>


""""""""""""""""""""""""""""""""" Keyboard Mappings: Jumping

"majutsushi/tagbar (outline)
nnoremap <silent> <leader>o :TagbarToggle<CR>

"beloglazov/vim-online-thesaurus
nnoremap <leader>d :OnlineThesaurusCurrentWord<cr>

nnoremap <c-j>q :Unite quickfix<CR>
nnoremap <c-j>j :Unite jump<CR>

"Jump to tag in vertical split instead of horizonal (default)
nnoremap <c-w>] :vertical wincmd ]<cr>

if !has("gui_running")
    "junegunn/fzf.vim
    nnoremap <c-j>t :Tag<CR>
    nnoremap g] :Tags '<C-r>=expand('<cword>')<CR> <CR>

    nnoremap g/ :Ag <C-r>=expand('<cword>')<CR><CR>
    nnoremap <c-j>; :BLines<CR>
    nnoremap <c-j>: :Lines<CR>

    command! -nargs=0 HgFiles call fzf#run({'source': 'hg sta -n', 'sink': 'e', 'options': ''})
    nnoremap <c-j>s :HgFiles<CR>
else
    " Shougo/unite.vim
    nnoremap <c-j>t :Unite tag<CR>
    nnoremap g] :Unite -input=<C-r>=expand('<cword>')<CR> tag<CR>

    nnoremap g/ :Unite -input=<C-r>=expand('<cword>')<CR> line<CR>
    nnoremap <c-j>; :Unite line<CR>
endif

" Edit the snippets for the filetype of the current buffer
" cskeeters/vim-snippets
nnoremap <C-j>es :OpenSnips<cr>

" Edit the maps file for the filetype of the current buffer
nnoremap <C-j>em :OpenMaps<cr>

" cskeeters/vim-jump
nmap <leader>gj <Plug>Jump
nnoremap <leader>mz :call GetMark('z')<cr>
nnoremap <leader>mx :call GetMark('x')<cr>
nnoremap <leader>mc :call GetMark('c')<cr>
nnoremap <leader>mv :call GetMark('v')<cr>

""""""""""""""""""""""""""""""""" Keyboard Mappings: Buffer Management
"cskeeters/closer.vim
nmap <C-j>c <Plug>OpenCloser

if !has("gui_running")
    "junegunn/fzf.vim
    noremap <C-j>b :Buffers<CR>
    noremap _      :Buffers<CR>
else
    " Shougo/unite.vim
    noremap <C-j>b :Unite buffer<CR>
    noremap _      :Unite buffer<CR>
endif

""""""""""""""""""""""""""""""""" Keyboard Mappings: File Search

" Shougo/unite.vim
" Bookmarks
noremap <leader><leader>b :UniteBookmarkAdd<cr>
noremap <C-j>k :Unite bookmark<CR>

if !has("gui_running")
    "junegunn/fzf.vim
    noremap <C-j>h :History<CR>
    noremap <C-j>m :Marks<CR>
    noremap <C-j>v :Files ~/.vim/plugged<CR>

    noremap <C-j><C-j> :Files<CR>
    noremap <C-j>f :Files<CR>
    "noremap <C-j><C-j> :Denite file_rec<CR>
    "noremap <C-j>f :Denite file_rec<CR>

    noremap <C-j>g :Ag<space>
else
    noremap <C-j>h :Unite file_mru<CR>
    noremap <C-j>v :Unite file:~/.vim/plugged<CR>

    noremap <C-j><C-j> :Unite file_rec/async<CR>
    noremap <C-j>f :Unite file_rec/async<CR>

    noremap <C-j>g :Unite grep:.<CR>
endif

let g:unite_source_menu_menus = get(g:,'unite_source_menu_menus',{})
let g:unite_source_menu_menus.projects = {'description' : 'Change Directory to favorties'}
let g:unite_source_menu_menus.projects.candidates = {
            \ 'notes':'~/Dropbox/notes',
            \ 'bcst-main':'~/Documents/nci/bcst',
            \ 'bcst-doc':'~/working/bcst-doc',
            \ 'dotfiles':'~/dotfiles',
            \ 'plugged':'~/.vim/plugged',
            \ 'rcmp':'~/Documents/nci/2014/mts/rcmp',
            \ 'working':'~/working',
            \ 'dhcis':'~/working/dhcis',
            \ 'vim-runtime':'/usr/local/Cellar/macvim/8.0-119/MacVim.app/Contents/Resources/vim/runtime'
            \ }

function! g:unite_source_menu_menus.projects.map(key, value)
    return {
    \   'word': a:key,
    \   'kind': 'command',
    \   'action__command': 'cd '.a:value.' | Dirvish'
    \ }
endfunction
noremap <silent><C-j>p :Unite -silent menu:projects<CR>


""""""""""""""""""""""""""""""""" Keyboard Mappings: Text Search
"mileszs/ack.vim
" This is better than :silent grep because
" * it respects .hgignore/.gitignore
" * grep requires <C-L> in iterm to redraw the screen
noremap <leader>/ :LAck <cword><cr>
noremap <leader>i/ :LAckWindow <cword><cr>


""""""""""""""""""""""""""""""""" Keyboard Mappings: File

noremap <Leader>s :update<CR>
" Use sudo and tee to write the file as root
nmap <leader><leader>w :w !sudo tee % >/dev/null<cr>


"cskeeters/vim-leave-window
nnoremap <leader>gw :LWClose!<cr>
nnoremap <leader>w :LWClose<cr>

noremap <leader>q :q<CR>

" cskeeters/vim-simple-alt
nmap <leader>l :Alt<cr>


""""""""""""""""""""""""""""""""" Keyboard Mappings: Text Manipulation

" Choose first spelling suggestion
nnoremap <localleader>. z=1<cr><cr>

" Remove trailing whitespace in current buffer
nnoremap <localleader><localleader>w :%s/\s\+$//<cr>

" Paste buffer as a sparate line
nnoremap <localleader>' :put "<cr>:normal ddkP<cr>

" cskeeters/vim-jump
nnoremap <localleader>z :put z<cr>
nnoremap <localleader>x :put x<cr>
nnoremap <localleader>c :put c<cr>
nnoremap <localleader>v :put v<cr>

" scrooloose/nerdcommenter
"map <localleader>c <plug>NERDCommenterComment
"let g:NERDCreateDefaultMappings=0

" cskeeters/vim-simple-comment
"nmap <localleader>cc <Plug>ToggleComment
"nmap <localleader>c <Plug>CommentOperator
"vmap <localleader>c <Plug>ToggleAllComment
vmap <localleader><localleader>c <Plug>MultiLineComment

" tpope/vim-commentary
xmap <localleader>c  <Plug>Commentary
nmap <localleader>c  <Plug>Commentary
omap <localleader>c  <Plug>Commentary
nmap <localleader>cc <Plug>CommentaryLine
nmap c<localleader>c <Plug>ChangeCommentary
nmap <localleader>cu <Plug>Commentary<Plug>Commentary

" mbbill/undotree
nnoremap <localleader><localleader>u :UndotreeToggle<CR>

" junegunn/vim-easy-align
vmap <Enter> <Plug>(EasyAlign)
nmap <Leader>a <Plug>(EasyAlign)

let g:unite_source_menu_menus = get(g:,'unite_source_menu_menus',{})

let g:unite_source_menu_menus.tabularize = {'description' : 'Tabularize'}
let g:unite_source_menu_menus.tabularize.candidates = { '|':'|', '=':'=', ':':':', ',':',' }

function! g:unite_source_menu_menus.tabularize.map(key, value)
    return {
    \   'word': a:key,
    \   'kind': 'command',
    \   'action__command': 'Tabularize /'.a:value
    \ }
endfunction
vnoremap <silent><space><space>t :Unite -silent menu:tabularize<CR>


""""""""""""""""""""""""""""""""" Keyboard Mappings: Abbr

iab <expr> dts strftime("%FT%T%z")
iab <expr> ds strftime("%Y-%b-%d")

""""""""""""""""""""""""""""""""" Keyboard Mappings: Other

nmap <C-k> :make<cr>

""""""""""""""""""""""""""""""""" Builtin: Configuration

"Disable netrw
let g:loaded_netrw       = 1
let g:loaded_netrwPlugin = 1

let g:netrw_liststyle=1
"let g:netrw_keepdir=0

" Enables % to work on html tags etc
" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif



""""""""""""""""""""""""""""""""" Plugins: Built-in Extension

call plug#begin()

Plug 'https://github.com/vim-scripts/argtextobj.vim'
" cia (change, in, argument)
Plug 'https://github.com/michaeljsmith/vim-indent-object'
" cii (change, in, indent)

Plug 'https://github.com/vim-scripts/visualrepeat'
Plug 'https://github.com/cskeeters/vim-smooth-scroll'
"let g:ms_per_line = 20
Plug 'https://github.com/tpope/vim-repeat'

if !has('nvim')
    "Speeds up Unite with asynchronous commands
    Plug 'https://github.com/Shougo/vimproc.vim', { 'do': 'make' }
endif


"Plug '~/working/base16-builder-php/templates/vim'

if version > 800
    " Addresses a possible bug where vim (term) doesn't fall back to underline
    " from undercurl
    let &t_Cs = "\e[4:3m"
    let &t_Ce = "\e[4:0m"
endif

Plug 'https://github.com/chriskempson/base16-vim',
    \ { 'do': 'git clone https://github.com/chriskempson/base16-shell.git ~/.vim/base16-shell' }
if $TERM != "konsole"
    " As a work around for the following bugs in kde4's konsole:
    " https://github.com/chriskempson/base16-shell/issues/31
    let g:base16_shell_path = $HOME."/.vim/base16-shell/scripts"
    let base16colorspace=256
endif
set background=dark

Plug 'https://github.com/junegunn/rainbow_parentheses.vim'
let g:rainbow#max_level = 16
let g:rainbow#pairs = [['(', ')'], ['[', ']'], ['{', '}']]
let g:rainbow#blacklist = [7, 10, 12]


""""""""""""""""""""""""""""""""" Plugins: Ease of use

Plug 'https://github.com/moll/vim-bbye'
Plug 'https://github.com/cskeeters/vim-leave-window'
Plug 'https://github.com/cskeeters/closer.vim'
Plug 'https://github.com/cskeeters/vim-simple-alt'
Plug 'https://github.com/cskeeters/vim-map-enter'
Plug 'https://github.com/mbbill/undotree'
Plug 'https://github.com/tpope/vim-abolish'
"Plug 'https://github.com/scrooloose/nerdcommenter'
Plug 'https://github.com/cskeeters/vim-simple-comment'
Plug 'https://github.com/tpope/vim-commentary'
Plug 'https://github.com/cskeeters/vim-diff-settings'

Plug 'https://github.com/majutsushi/tagbar'
" Add support for markdown files in tagbar.
" https://github.com/majutsushi/tagbar/wiki#markdown
let g:tagbar_type_markdown = {
    \ 'ctagstype': 'markdown',
    \ 'ctagsbin' : '~/bin/markdown2ctags.py',
    \ 'ctagsargs' : '-f - --sort=yes',
    \ 'kinds' : [
        \ 's:sections',
        \ 'i:images'
    \ ],
    \ 'sro' : '|',
    \ 'kind2scope' : {
        \ 's' : 'section',
    \ },
    \ 'sort': 0,
\ }
let g:tagbar_autoclose = 1
let g:tagbar_autofocus = 1


"Plug 'https://github.com/Lokaltog/vim-easymotion'
"Plug 'https://github.com/tpope/vim-vinegar'

Plug 'https://github.com/justinmk/vim-dirvish'

Plug 'https://github.com/mileszs/ack.vim'
if executable('ag')
    let g:ackprg = 'ag --nogroup --nocolor --column'
endif

Plug 'https://github.com/junegunn/vim-easy-align'

"junegunn/vim-easy-align doesn't work for tables
Plug 'https://github.com/godlygeek/tabular'

Plug 'https://github.com/cskeeters/vim-jump'

""""""""""""""""""""""""""""""""" Plugins: File Searcher

" FZF requires a terminal emulator.  For this to work in MacVim, XQuartz must
" be installed so xterm can be run
if !has("gui_running")
    " This defines :FZF
    "If installed with brew, we don't need this
    "Plug '/usr/local/opt/fzf'
    Plug 'https://github.com/junegunn/fzf'

    " Adds useful commands for fzf
    Plug 'https://github.com/junegunn/fzf.vim'

    let g:fzf_layout = {'up': '~100%'}
    let g:fzf_files_options = '--reverse --preview "(highlight -O ansi {} || cat {}) 2> /dev/null | head -'.&lines.'"'
    let g:fzf_buffers_jump = 1
    let g:fzf_tags_command = 'ctags -R'
else
    Plug 'https://github.com/Shougo/neomru.vim'
    Plug 'https://github.com/tsukkee/unite-tag'
endif


Plug 'https://github.com/cskeeters/unite-fzf'
Plug 'https://github.com/Shougo/neoyank.vim'
Plug 'https://github.com/osyo-manga/unite-quickfix'
Plug 'https://github.com/Shougo/unite-outline'
Plug 'https://github.com/Shougo/unite-help'

let g:unite_source_history_yank_enable = 1
let g:unite_source_grep_command = 'ag'
let g:unite_source_grep_default_opts = '-i --vimgrep --hidden --ignore ''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'''
let g:unite_source_rec_async_command = ['ag', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', '']
let g:unite_enable_auto_select = 0

if has('nvim')
    " Requires python3.  Run
    "   pip3 install neovim
    Plug 'https://github.com/Shougo/denite.nvim'
endif
Plug 'https://github.com/Shougo/unite.vim'

""""""""""""""""""""""""""""""""" Plugins: Tab Completion

Plug 'https://github.com/ervandew/supertab'
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabClosePreviewOnPopupClose = 0

"Plug 'https://github.com/Valloric/YouCompleteMe'
"Disable signs so that signify can work
let g:ycm_enable_diagnostic_signs = 0
let g:ycm_extra_conf_globlist = ['~/rcmp/*','!~/*']
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'


""""""""""""""""""""""""""""""""" Plugins: snippets

if g:speed < 1
    Plug 'https://github.com/SirVer/ultisnips'
endif
"let g:UltiSnipsSnippetsDir = "~/.vim/plugged/vim-snippets/UltiSnips"
"let g:UltiSnipsJumpForwardTrigger="<c-b>"
"let g:UltiSnipsJumpBackwardTrigger="<c-z>"
"let g:UltiSnipsExpandTrigger="<c-b>"
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

"Plug 'https://github.com/tomtom/tlib_vim'
"Plug 'https://github.com/MarcWeber/vim-addon-mw-utils'
"Plug 'https://github.com/garbas/vim-snipmate'

" vim runtime/filetype autoload/dist/ft.vim will detect htmldjango.
" This dot syntax makes html snippets accessible
autocmd FileType htmldjango set ft=htmldjango.js.css.html
autocmd FileType html set ft=js.css.html

" Personal snippets
Plug 'https://github.com/cskeeters/vim-snippets'


""""""""""""""""""""""""""""""""" Plugins: DRCS git/hg

" Show diff in gutter
Plug 'https://github.com/mhinz/vim-signify'
let g:signify_vcs_list = ['hg']
let g:signify_disable_by_default = 1

Plug 'https://github.com/tpope/vim-fugitive'
":Gblame :Gdiff

Plug 'https://github.com/jlfwong/vim-mercenary'
":HGblame :HGdiff :HGshow

Plug 'https://github.com/cskeeters/vim-hg'

Plug 'https://github.com/cskeeters/vim-vcvars'
Plug 'https://github.com/cskeeters/vim-statusline'

""""""""""""""""""""""""""""""""" Plugins: Lookup/Help
if has('osx')
    Plug 'https://github.com/rizzatti/dash.vim'
endif

Plug 'https://github.com/beloglazov/vim-online-thesaurus'
let g:online_thesaurus_map_keys = 0

"
""""""""""""""""""""""""""""""""" Plugins: File-type specific

"keyboard mappings and settings per file type
Plug 'https://github.com/cskeeters/vim-maps'

if g:speed < 1
    " Use custom cskeeters/vim-markdown
    let g:polyglot_disabled = ['markdown']
    Plug 'https://github.com/sheerun/vim-polyglot'
endif

Plug 'https://github.com/cskeeters/sr.vim'

""""""""""""""""""""""""""""""""" Plugins: Markdown
" from plasticboy/vim-markdown without netrw#BrowseX
Plug 'https://github.com/cskeeters/vim-markdown'
" Disable ]c to move to header since it disrupts ]c - next difference
map <Plug> <Plug>Markdown_MoveToCurHeader
let g:vim_markdown_folding_disabled = 1

Plug 'https://github.com/cskeeters/vim-markdown-maps'

Plug 'https://github.com/cskeeters/vim-md-doc'
let g:md_doc = [
            \ ["/Users/chad/working/bcst-doc", "bcst-doc"],
            \ ["/Users/chad/Dropbox/notes", "notes"] ]
let g:md_doc_auto_commit = 0

Plug 'https://github.com/itspriddle/vim-marked'
" Use Marked (version 1)
let g:marked_app = "Marked"

""""""""""""""""""""""""""""""""" Plugins: HTML
Plug 'https://github.com/alvan/vim-closetag'


""""""""""""""""""""""""""""""""" Plugins: Java
Plug 'https://github.com/cskeeters/javadoc.vim', { 'for': 'java' }
let g:javadoc_path="/Users/chad/java8_doc/api"


Plug 'https://github.com/cskeeters/jcall.vim', { 'for': 'java' }
let g:jcall_debug = 0
let g:jcall_src_build_pairs = [
            \ ['/Users/chad/jcall_test/src', '/Users/chad/jcall_test/build'],
            \ ]

Plug 'https://github.com/cskeeters/vim-log4j', { 'for': 'java' }

""""""""""""""""""""""""""""""""" Plugins: c++

" Plug 'https://github.com/myint/clang-complete', { 'for': 'cpp' }
" let g:clang_library_path='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib'


" IF syntastic is used
"let g:syntastic_cpp_compiler_options = ' -std=c++11 -D_GLIBCXX_USE_NANOSLEEP'
"let g:syntastic_cpp_compiler_options .= ' `pkg-config --cflags --libs cairo'
"let g:syntastic_cpp_compiler_options .= ' `pkg-config --cflags --libs cairomm-1.0'

"let g:syntastic_cpp_compiler = 'clang++'
"let g:syntastic_cpp_compiler_options = ' -std=c++11 -stdlib=libc++'


""""""""""""""""""""""""""""""""" Plugins: experimental

call plug#end()


""""""""""""""""""""""""""""""""" Plugins: post-load Configuration

function! FocusWindow(target_width)
    let l:winid = win_getid()
    let l:winlist = getwininfo()

    " In case we were called by accident, just exit
    if len(l:winlist) < 2
        return
    endif

    for winfo in l:winlist
        if winfo.winid == l:winid
            if winfo.width != a:target_width
                execute "vertical resize ".a:target_width
            else
                wincmd =
            endif
        endif
    endfor
endfunction

if has('nvim')
    call denite#custom#source('file_rec', 'matchers', ['matcher_ignore_globs'])
endif
call unite#custom#profile('default', 'context', { 'start_insert':1, 'prompt':'>', 'no_split':1, 'wipe':1 })
"call unite#filters#matcher_default#use(['matcher_fuzzy'])
"call unite#filters#matcher_default#use(['matcher_glob'])
call unite#filters#matcher_default#use(['matcher_fzf'])

"call unite#filters#sorter_default#use(['sorter_rank'])


""""""""""""""""""""""""""""""""" Configuration: colorscheme
if has('nvim')
    if $TERM_PROGRAM == "iTerm.app"
        set termguicolors
    endif
endif

" Allow color schemes to do bright colors without forcing bold.
if &t_Co == 8 && $TERM !~# '^Eterm'
  set t_Co=16
endif

if g:speed < 1
    " Load matchit.vim, but only if the user hasn't installed a newer version.
    if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
        runtime! macros/matchit.vim
    endif
endif

if g:speed < 2
    if has('autocmd')
        filetype plugin indent on
    endif

    colorscheme base16-default-dark
    " Vim 8 sets cterm=underline, reset that here
    highlight CursorLine   ctermbg=18 term=NONE cterm=NONE
    highlight CursorLineNr ctermbg=18 term=NONE cterm=NONE
elseif g:speed > 2
    hi clear
    syntax off
endif
