#!/usr/bin/env sh

IFS="$(printf '\n\r')"

. "$(dirname "$0")"/.nnn-plugin-helper

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}
# Add 0 so it matches find -print0 type data stream
printf '\0' >> $selection

while read -d $'\0' PDF_PATH ; do
    echo "Opening: $PDF_PATH"
    open -a "/Applications/Adobe Acrobat DC/Adobe Acrobat.app" "$PDF_PATH"
done < "$selection"

# Clear selections
if [ -p "$NNN_PIPE" ]; then
    printf "-" > "$NNN_PIPE"
fi
