#!/usr/bin/env sh

IFS="$(printf '\n\r')"

. "$(dirname "$0")"/.nnn-plugin-helper

# CTX=1
# Use the current context (tab).  Don't ask the user
CUR_CTX=1

if ! type fzf >/dev/null 2>&1; then
    printf "fzf missing"
    read -r _
    exit 1
fi

sel=$(find "$(realpath .)" -type d | fzf)

if [ -n "$sel" ]; then
    if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
        exit 0
    fi

    echo "cding to $sel"
    nnn_cd "$sel" "$CTX" ;
fi
