link cmd/bcst.snippets                      .config/cmd
link cmd/beancount.snippets                 .config/cmd
link cmd/chroma.snippets                    .config/cmd
link cmd/copyparty.snippets                 .config/cmd
link cmd/gpg.snippets                       .config/cmd
link cmd/gpg.sh                             .config/cmd
link cmd/joffrey.snippets                   .config/cmd
link cmd/magick.snippets                    .config/cmd
link cmd/ollama.snippets                    .config/cmd
link cmd/ollama.sh                          .config/cmd
link cmd/server.snippets                    .config/cmd
link cmd/yaml_finance.snippets              .config/cmd
