link cmd/ag.snippets                        .config/cmd
link cmd/beancount.snippets                 .config/cmd
link cmd/bind.snippets                      .config/cmd
link cmd/brew.snippets                      .config/cmd
link cmd/cargo.snippets                     .config/cmd
link cmd/checksum.snippets                  .config/cmd
link cmd/chroma.snippets                    .config/cmd
link cmd/copyparty.snippets                 .config/cmd
link cmd/disc.snippets                      .config/cmd
link cmd/docker.snippets                    .config/cmd
link cmd/git.snippets                       .config/cmd
link cmd/gnu.snippets                       .config/cmd
link cmd/go.snippets                        .config/cmd
link cmd/joffrey.snippets                   .config/cmd
link cmd/luarocks.snippets                  .config/cmd
link cmd/magick.snippets                    .config/cmd
link cmd/mediainfo.snippets                 .config/cmd
link cmd/net.snippets                       .config/cmd
link cmd/npm.snippets                       .config/cmd
link cmd/ollama.snippets                    .config/cmd
link cmd/python.snippets                    .config/cmd
link cmd/pyvenv.snippets                    .config/cmd
link cmd/restic.snippets                    .config/cmd
link cmd/rsync.snippets                     .config/cmd
link cmd/tar.snippets                       .config/cmd
link cmd/tmux.snippets                      .config/cmd
link cmd/uv.snippets                        .config/cmd
link cmd/yaml_finance.snippets              .config/cmd
link cmd/zip.snippets                       .config/cmd
