link cmd/apt.snippets                       .config/cmd
link cmd/beancount.snippets                 .config/cmd
link cmd/beet.snippets                      .config/cmd
link cmd/git.snippets                       .config/cmd
link cmd/gnu.snippets                       .config/cmd
link cmd/luarocks.snippets                  .config/cmd
link cmd/mediainfo.snippets                 .config/cmd
link cmd/restic.snippets                    .config/cmd
link cmd/tar.snippets                       .config/cmd
link cmd/uv.snippets                        .config/cmd
link cmd/zip.snippets                       .config/cmd
